checks:
  complex-logic:
    config:
      threshold: 6
  method-complexity:
    enabled: true
    config:
      threshold: 6
  method-lines:
    enabled: true 
  nested-control-flow:
    enabled: false 
exclude_patterns:
- "**/test/"
- "**/androidTest/"
- "**test"
