checks:
  complex-logic:
    config:
      threshold: 6
  method-complexity:
    enabled: true
    config:
      threshold: 6
  method-lines:
    enabled: true 
    config:
      threshold: 40
  nested-control-flow:
    enabled: false 
exclude_patterns:
- "**/test/"
- "**/androidTest/"
- "**test"
- "**/main/java/com/sdp/swiftwallet/di/"
- "**/main/java/com/sdp/swiftwallet/domain/model/CurrencyBank.java"
- "**/main/java/com/sdp/swiftwallet/domain/model/RequestQueueCurrencyPriceChecker.java"
